import os
import httpx
import json
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

UPSTAGE_API_KEY = os.getenv("UPSTAGE_API_KEY")
UPSTAGE_CHAT_URL = "https://api.upstage.ai/v1/solar/chat/completions"

async def get_ai_response(user_message: str, target_career: str = "Undecided", history: list = []) -> dict:
    """
    Real Chat with Coach Dokyung (Solar LLM) returning JSON.
    Context injected via 'history' list: [{"role": "user", "content": "..."}]
    """
    if not UPSTAGE_API_KEY:
        # Mock logic matching the new schema
        return {
            "analysis": {
                "emotion_intensity": 5,
                "anxiety_theme": "D",
                "defense_mechanism": "DM01",
                "career_alignment_score": 50,
                "user_mood": "Mock State (No API Key)"
            },
            "coach_thought": "Mocking response due to missing API key.",
            "message_to_user": "API Key가 설정되지 않았습니다. .env 파일을 확인해주세요.",
            "suggested_action": {
                "title": "API Key 설정하기",
                "duration_min": 5,
                "type": "start"
            }
        }

    # Current Day for Context
    today_str = datetime.now().strftime("%Y-%m-%d (%A)")

    system_prompt = f"""
    You are Dogyeong (도경), a reliable and supportive 'Senior' (Sunbae/선배) coach for university students.
    Your tone should be casual but polite (Haeyo-che/해요체), warm, and concise.
    AVOID being robotic or repetitive.
    
    Target Career of User: {target_career}
    Current Date: {today_str}

    [Operational Protocol]
    1. Analyze: briefly.
    2. Action-Oriented: If the user agrees to a suggestion, EXECUTE it using 'server_action' instead of just saying you will.
    3. Tool Use: 
       - If user says "Add a schedule" or "I'll rest", generate a 'create_task' action.
       - 'due_date' should be inferred from user input (e.g. "Tomorrow" -> calculate date). Default to today if unsure.

    [Response Format]
    You must ALWAYS return values in the following JSON format:
    {{
      "analysis": {{
        "emotion_intensity": 0-10,
        "anxiety_theme": "Code (A~J or null)",
        "defense_mechanism": "Code (DM01~10 or null)",
        "career_alignment_score": 0-100,
        "user_mood": "Short summary"
      }},
      "coach_thought": "Brief internal reasoning. If user accepted suggestion, set action.",
      "message_to_user": "Natural Korean response. If action taken, say 'Done/Registered'.",
      "suggested_action": {{
        "title": "Action Title",
        "duration_min": 10,
        "type": "start" # or 'rest' or 'drop'
      }} or null,
      "server_action": {{
         "action_type": "create_task",
         "data": {{ 
             "title": "Task Title", 
             "description": "Generated by Coach",
             "due_date": "YYYY-MM-DD" 
         }}
      }} or null
    }}
    """

    headers = {
        "Authorization": f"Bearer {UPSTAGE_API_KEY}",
        "Content-Type": "application/json"
    }
    
    # Construct Messages: System -> History -> Current User Msg
    messages_payload = [{"role": "system", "content": system_prompt}]
    
    # Add history (limit to last 10 turns to save tokens)
    for msg in history[-10:]:
        messages_payload.append(msg)

    messages_payload.append({"role": "user", "content": user_message})
    
    payload = {
        "model": "solar-1-mini-chat",
        "messages": messages_payload,
        "response_format": { "type": "json_object" }
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(UPSTAGE_CHAT_URL, headers=headers, json=payload, timeout=30.0)
            response.raise_for_status()
            content = response.json()["choices"][0]["message"]["content"]
            result = json.loads(content)
            
            # Defensive coding: Ensure server_action is None if missing
            if "server_action" not in result:
                result["server_action"] = None
                
            return result
        except Exception as e:
            print(f"Chat Error: {e}")
            return {
                "analysis": { "emotion_intensity": 0, "user_mood": "Error" },
                "coach_thought": "Error occurred.",
                "message_to_user": "도경이와 연결이 불안정해요. 잠시 후 다시 시도해주세요.",
                "suggested_action": None,
                "server_action": None
            }
